FROM php:8.0.13-fpm

RUN apt update -y
RUN apt install -y \
        cron systemd vim 
RUN systemctl enable cron.service

ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/

RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions gd mysqli iconv zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/
RUN ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

CMD bash -c "cron && php-fpm"